# New Questions Test Notebook

In [2]:
# Importing required libraries, setting up logging, and loading questions
import logging
import random  # noqa: F401
from typing import List, Optional  # noqa: F401

import pandas as pd
from IPython.display import display
from pandas.io.formats.style import Styler

from pybatfish.client.session import Session  # noqa: F401

# noinspection PyUnresolvedReferences
from pybatfish.datamodel import Edge, Interface  # noqa: F401
from pybatfish.datamodel.answer import TableAnswer
from pybatfish.datamodel.flow import HeaderConstraints, PathConstraints  # noqa: F401
from pybatfish.datamodel.route import BgpRoute  # noqa: F401
from pybatfish.util import get_html

# Configure all pybatfish loggers to use WARN level
logging.getLogger("pybatfish").setLevel(logging.WARN)

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
# Prevent rendering text between '$' as MathJax expressions
pd.set_option("display.html.use_mathjax", False)

# UUID for CSS styles used by pandas styler.
# Keeps our notebook HTML deterministic when displaying dataframes
_STYLE_UUID = "pybfstyle"


class MyStyler(Styler):
    """A custom styler for displaying DataFrames in HTML"""

    def __repr__(self):
        return repr(self.data)


def show(df):
    """
    Displays a dataframe as HTML table.

    Replaces newlines and double-spaces in the input with HTML markup, and
    left-aligns the text.
    """
    if isinstance(df, TableAnswer):
        df = df.frame()

    # workaround for Pandas bug in Python 2.7 for empty frames
    if not isinstance(df, pd.DataFrame) or df.size == 0:
        display(df)
        return
    display(
        MyStyler(df)
        .set_uuid(_STYLE_UUID)
        .format(get_html)
        .set_properties(**{"text-align": "left", "vertical-align": "top"})
    )

In [4]:
bf = Session(host="localhost")

## Load a network snapshot

In [ ]:
NETWORK_NAME = "internet2"
SNAPSHOT_PATH = r"\config2spec\scenarios\internet2"  
# change this to your snapshot path

bf.set_network(NETWORK_NAME)
bf.init_snapshot(SNAPSHOT_PATH, name="snapshot")

'snapshot'

## CommunityMatchUsage
Lists number of community match expressions each node uses.

In [6]:
result = bf.q.communityMatchUsage().answer().frame()
result

       Node Community_Match_Count
0  atla-re0                    72
1  chic-re0                   189
2  clev-re0                    58
3  hous-re0                    64
4  kans-re0                    76
5  losa-re0                   357
6  newy-re0                   163
7  salt-re0                    74
8  seat-re0                   155
9  wash-re0                   163

## CommunityReferences
Lists community match expressions and the nodes that reference them.

In [7]:
result = bf.q.communityReferences().answer().frame()
result

,Community,Node_List,Node_Count
0,ALL-COMMS,"['chic-re0', 'clev-re0', 'losa-re0', 'newy-re0', 'salt-re0', 'seat-re0', 'wash-re0']",7
1,BLOCK-TO-COMMERCIAL,"['atla-re0', 'chic-re0', 'clev-re0', 'hous-re0', 'kans-re0', 'losa-re0', 'newy-re0', 'salt-re0', 'seat-re0', 'wash-re0']",10
2,BLOCK-TO-EXTERNAL,"['atla-re0', 'chic-re0', 'clev-re0', 'hous-re0', 'kans-re0', 'losa-re0', 'newy-re0', 'salt-re0', 'seat-re0', 'wash-re0']",10
3,CLEARSPAN,"['hous-re0', 'newy-re0']",2
4,CLEAR_COMMUNITIES_FROMCUST,['losa-re0'],1
...,...,...,...
574,TRMIGRATION,"['atla-re0', 'chic-re0', 'clev-re0', 'hous-re0', 'kans-re0', 'losa-re0', 'newy-re0', 'salt-re0', 'seat-re0', 'wash-re0']",10
575,TRMIGRATION-GPN,"['chic-re0', 'kans-re0']",2
576,WILDCARD-ANY-AS11164,['losa-re0'],1
577,ion-test,['wash-re0'],1
578,ion-test-b,['hous-re0'],1

## RouteFilterUsers
Lists number of route filters each node uses.

In [8]:
result = bf.q.routeFilterUsers().answer().frame()
result

       Node Route_Filter_Count
0  atla-re0                143
1  chic-re0                300
2  clev-re0                125
3  hous-re0                153
4  kans-re0                178
5  losa-re0                171
6  newy-re0                185
7  salt-re0                102
8  seat-re0                140
9  wash-re0                256

## TiebreakerUsage
Lists the BGP tiebreaker used by each node.

In [9]:
result = bf.q.tiebreakerUsage().answer().frame()
result

,Tiebreaker,Node_List,Node_Count
0,ARRIVAL_ORDER,"['atla-re0', 'chic-re0', 'clev-re0', 'hous-re0', 'kans-re0', 'losa-re0', 'newy-re0', 'salt-re0', 'seat-re0', 'wash-re0']",10

## MultipathMatchUsage
Lists nodes by their multipath match mode. Nodes without both EBGP and IBGP multipath enabled are grouped under N/A.

In [10]:
result = bf.q.multipathMatchUsage().answer().frame()
result

,Match_Mode,Node_List,Node_Count
0,N/A,"['atla-re0', 'chic-re0', 'clev-re0', 'hous-re0', 'kans-re0', 'losa-re0', 'newy-re0', 'salt-re0', 'seat-re0', 'wash-re0']",10

## AsPathUsage
Lists AS paths and the nodes that have routes using that path.

In [11]:
result = bf.q.asPathUsage().answer().frame()
result

BatfishException: Work finished with status WorkStatusCode.REQUEUEFAILURE
work_item: {"containerName": "internet2", "id": "82af6876-151d-468c-bc83-af352a33dfd1", "requestParams": {"answer": "", "questionname": "__asPathUsage_48c0a01e-b1e3-484a-9f8e-2e631e0a6ef7", "testrig": "snapshot"}, "testrigName": "snapshot"}
task_details: {'args': None, 'batches': [{'completed': 0, 'description': "Couldn't requeue after unblocking.\nCannot queue dataplane dependent work for 17de54d5-811d-46b5-9687-8e724e4df59b: Status is DATAPLANING_FAIL but no incomplete dataplaning work exists", 'size': 0, 'startDate': '2026-04-10T16:34:08.298+00:00'}], 'errMessage': None, 'obtained': '2026-04-10T16:34:08.298+00:00', 'status': 'RequeueFailure', 'terminated': None}

## BgpPropertiesCount
Counts BGP process properties across nodes.

In [12]:
result = bf.q.bgpPropertiesCount().answer().frame()
result

,Node_Structure_Name,Community_Set_Vals,Set_Metric,Match_Community_Vals,Local_Preference
0,atla-re0 AL2S-IN-INBAND-BACKUP,0,0,0,1
1,atla-re0 AL2S-IN-INBAND-PRIMARY,0,0,0,1
2,atla-re0 AL2S-IN-OOB-BACKUP,0,0,0,1
3,atla-re0 AL2S-IN-OOB-PRIMARY,0,0,0,1
4,atla-re0 AL2S-OUT-INBAND-BACKUP,0,0,0,0
...,...,...,...,...,...
1514,wash-re0 WORLDBANK-IN6,0,0,0,0
1515,wash-re0 WSU-IN,0,0,0,0
1516,wash-re0 ion-test,0,0,1,0
1517,wash-re0 load-balancing-policy,0,0,0,0
1518,wash-re0 pim-join-filter,0,0,0,0

## CommunitySetRegex
Lists community set match expression names and corresponding regular expressions.

In [13]:
result = bf.q.communitySetRegex().answer().frame()
result

                 Structure_Name                    Regex
0                     ALL-COMMS                    .*:.*
1    CLEAR_COMMUNITIES_FROMCUST         ^11164:[1,7-9]*$
2               CPS-AS10310-OUT                 .*:10310
3               CPS-AS11164-OUT                 .*:11164
4               CPS-AS11274-OUT                 .*:11274
..                          ...                      ...
248            NETPLUS-PREPEND2                 65002:.*
249            NETPLUS-PREPEND3                 65003:.*
250                TO-CPS-PEERS  ^11164:((7880)|(7890))$
251            TRCPS_WASH_19782            65000:19782:1
252        WILDCARD-ANY-AS11164             ^11164:(.*)$

[253 rows x 2 columns]

## SubnetworkPolicies
Lists routing policies between routers within a subnetwork.

In [14]:
result = bf.q.subnetworkPolicies().answer().frame()
result

,Node,Policy_Name,Policy_Type,Policy_Definition
0,atla-re0,NEXT-HOP-SELF,Export_Routing_Policy,"{""name"":""NEXT-HOP-SELF"",""statements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""comment"":""__NEXT-HOP-SELF__DEFAULT_TERM__"",""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.MatchProtocol"",""protocols"":[""bgp"",""ibgp""]},""trueStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.TraceableStatement"",""innerStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.SetNextHop"",""expr"":{""class"":""org.batfish.datamodel.routing_policy.expr.SelfNextHop""}}],""traceElement"":{""fragments"":[{""class"":""org.batfish.datamodel.TraceElement$TextFragment"",""text"":""Matched ""},{""class"":""org.batfish.datamodel.TraceElement$LinkFragment"",""text"":""policy-statement NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""vendorStructureId"":{""filename"":""configs/atla.conf"",""structureName"":""NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""structureType"":""policy-statement term""}}]}}]},{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""falseStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.Statements$StaticStatement"",""type"":""Return""}],""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.BooleanExprs$StaticBooleanExpr"",""type"":""CallExprContext""}}]}"
1,chic-re0,NEXT-HOP-SELF,Export_Routing_Policy,"{""name"":""NEXT-HOP-SELF"",""statements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""comment"":""__NEXT-HOP-SELF__DEFAULT_TERM__"",""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.MatchProtocol"",""protocols"":[""bgp"",""ibgp""]},""trueStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.TraceableStatement"",""innerStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.SetNextHop"",""expr"":{""class"":""org.batfish.datamodel.routing_policy.expr.SelfNextHop""}}],""traceElement"":{""fragments"":[{""class"":""org.batfish.datamodel.TraceElement$TextFragment"",""text"":""Matched ""},{""class"":""org.batfish.datamodel.TraceElement$LinkFragment"",""text"":""policy-statement NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""vendorStructureId"":{""filename"":""configs/chic.conf"",""structureName"":""NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""structureType"":""policy-statement term""}}]}}]},{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""falseStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.Statements$StaticStatement"",""type"":""Return""}],""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.BooleanExprs$StaticBooleanExpr"",""type"":""CallExprContext""}}]}"
2,clev-re0,NEXT-HOP-SELF,Export_Routing_Policy,"{""name"":""NEXT-HOP-SELF"",""statements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""comment"":""__NEXT-HOP-SELF__DEFAULT_TERM__"",""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.MatchProtocol"",""protocols"":[""bgp"",""ibgp""]},""trueStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.TraceableStatement"",""innerStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.SetNextHop"",""expr"":{""class"":""org.batfish.datamodel.routing_policy.expr.SelfNextHop""}}],""traceElement"":{""fragments"":[{""class"":""org.batfish.datamodel.TraceElement$TextFragment"",""text"":""Matched ""},{""class"":""org.batfish.datamodel.TraceElement$LinkFragment"",""text"":""policy-statement NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""vendorStructureId"":{""filename"":""configs/clev.conf"",""structureName"":""NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""structureType"":""policy-statement term""}}]}}]},{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""falseStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.Statements$StaticStatement"",""type"":""Return""}],""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.BooleanExprs$StaticBooleanExpr"",""type"":""CallExprContext""}}]}"
3,hous-re0,NEXT-HOP-SELF,Export_Routing_Policy,"{""name"":""NEXT-HOP-SELF"",""statements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""comment"":""__NEXT-HOP-SELF__DEFAULT_TERM__"",""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.MatchProtocol"",""protocols"":[""bgp"",""ibgp""]},""trueStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.TraceableStatement"",""innerStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.SetNextHop"",""expr"":{""class"":""org.batfish.datamodel.routing_policy.expr.SelfNextHop""}}],""traceElement"":{""fragments"":[{""class"":""org.batfish.datamodel.TraceElement$TextFragment"",""text"":""Matched ""},{""class"":""org.batfish.datamodel.TraceElement$LinkFragment"",""text"":""policy-statement NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""vendorStructureId"":{""filename"":""configs/hous.conf"",""structureName"":""NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""structureType"":""policy-statement term""}}]}}]},{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""falseStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.Statements$StaticStatement"",""type"":""Return""}],""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.BooleanExprs$StaticBooleanExpr"",""type"":""CallExprContext""}}]}"
4,kans-re0,NEXT-HOP-SELF,Export_Routing_Policy,"{""name"":""NEXT-HOP-SELF"",""statements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""comment"":""__NEXT-HOP-SELF__DEFAULT_TERM__"",""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.MatchProtocol"",""protocols"":[""bgp"",""ibgp""]},""trueStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.TraceableStatement"",""innerStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.SetNextHop"",""expr"":{""class"":""org.batfish.datamodel.routing_policy.expr.SelfNextHop""}}],""traceElement"":{""fragments"":[{""class"":""org.batfish.datamodel.TraceElement$TextFragment"",""text"":""Matched ""},{""class"":""org.batfish.datamodel.TraceElement$LinkFragment"",""text"":""policy-statement NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""vendorStructureId"":{""filename"":""configs/kans.conf"",""structureName"":""NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""structureType"":""policy-statement term""}}]}}]},{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""falseStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.Statements$StaticStatement"",""type"":""Return""}],""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.BooleanExprs$StaticBooleanExpr"",""type"":""CallExprContext""}}]}"
5,losa-re0,NEXT-HOP-SELF,Export_Routing_Policy,"{""name"":""NEXT-HOP-SELF"",""statements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""comment"":""__NEXT-HOP-SELF__DEFAULT_TERM__"",""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.MatchProtocol"",""protocols"":[""bgp"",""ibgp""]},""trueStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.TraceableStatement"",""innerStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.SetNextHop"",""expr"":{""class"":""org.batfish.datamodel.routing_policy.expr.SelfNextHop""}}],""traceElement"":{""fragments"":[{""class"":""org.batfish.datamodel.TraceElement$TextFragment"",""text"":""Matched ""},{""class"":""org.batfish.datamodel.TraceElement$LinkFragment"",""text"":""policy-statement NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""vendorStructureId"":{""filename"":""configs/losa.conf"",""structureName"":""NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""structureType"":""policy-statement term""}}]}}]},{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""falseStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.Statements$StaticStatement"",""type"":""Return""}],""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.BooleanExprs$StaticBooleanExpr"",""type"":""CallExprContext""}}]}"
6,newy-re0,NEXT-HOP-SELF,Export_Routing_Policy,"{""name"":""NEXT-HOP-SELF"",""statements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""comment"":""__NEXT-HOP-SELF__DEFAULT_TERM__"",""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.MatchProtocol"",""protocols"":[""bgp"",""ibgp""]},""trueStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.TraceableStatement"",""innerStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.SetNextHop"",""expr"":{""class"":""org.batfish.datamodel.routing_policy.expr.SelfNextHop""}}],""traceElement"":{""fragments"":[{""class"":""org.batfish.datamodel.TraceElement$TextFragment"",""text"":""Matched ""},{""class"":""org.batfish.datamodel.TraceElement$LinkFragment"",""text"":""policy-statement NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""vendorStructureId"":{""filename"":""configs/newy32aoa.conf"",""structureName"":""NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""structureType"":""policy-statement term""}}]}}]},{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""falseStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.Statements$StaticStatement"",""type"":""Return""}],""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.BooleanExprs$StaticBooleanExpr"",""type"":""CallExprContext""}}]}"
7,salt-re0,NEXT-HOP-SELF,Export_Routing_Policy,"{""name"":""NEXT-HOP-SELF"",""statements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""comment"":""__NEXT-HOP-SELF__DEFAULT_TERM__"",""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.MatchProtocol"",""protocols"":[""bgp"",""ibgp""]},""trueStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.TraceableStatement"",""innerStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.SetNextHop"",""expr"":{""class"":""org.batfish.datamodel.routing_policy.expr.SelfNextHop""}}],""traceElement"":{""fragments"":[{""class"":""org.batfish.datamodel.TraceElement$TextFragment"",""text"":""Matched ""},{""class"":""org.batfish.datamodel.TraceElement$LinkFragment"",""text"":""policy-statement NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""vendorStructureId"":{""filename"":""configs/salt.conf"",""structureName"":""NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""structureType"":""policy-statement term""}}]}}]},{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""falseStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.Statements$StaticStatement"",""type"":""Return""}],""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.BooleanExprs$StaticBooleanExpr"",""type"":""CallExprContext""}}]}"
8,seat-re0,NEXT-HOP-SELF,Export_Routing_Policy,"{""name"":""NEXT-HOP-SELF"",""statements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""comment"":""__NEXT-HOP-SELF__DEFAULT_TERM__"",""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.MatchProtocol"",""protocols"":[""bgp"",""ibgp""]},""trueStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.TraceableStatement"",""innerStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.SetNextHop"",""expr"":{""class"":""org.batfish.datamodel.routing_policy.expr.SelfNextHop""}}],""traceElement"":{""fragments"":[{""class"":""org.batfish.datamodel.TraceElement$TextFragment"",""text"":""Matched ""},{""class"":""org.batfish.datamodel.TraceElement$LinkFragment"",""text"":""policy-statement NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""vendorStructureId"":{""filename"":""configs/seat.conf"",""structureName"":""NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""structureType"":""policy-statement term""}}]}}]},{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""falseStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.Statements$StaticStatement"",""type"":""Return""}],""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.BooleanExprs$StaticBooleanExpr"",""type"":""CallExprContext""}}]}"
9,wash-re0,NEXT-HOP-SELF,Export_Routing_Policy,"{""name"":""NEXT-HOP-SELF"",""statements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""comment"":""__NEXT-HOP-SELF__DEFAULT_TERM__"",""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.MatchProtocol"",""protocols"":[""bgp"",""ibgp""]},""trueStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.TraceableStatement"",""innerStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.SetNextHop"",""expr"":{""class"":""org.batfish.datamodel.routing_policy.expr.SelfNextHop""}}],""traceElement"":{""fragments"":[{""class"":""org.batfish.datamodel.TraceElement$TextFragment"",""text"":""Matched ""},{""class"":""org.batfish.datamodel.TraceElement$LinkFragment"",""text"":""policy-statement NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""vendorStructureId"":{""filename"":""configs/wash.conf"",""structureName"":""NEXT-HOP-SELF term __NEXT-HOP-SELF__DEFAULT_TERM__"",""structureType"":""policy-statement term""}}]}}]},{""class"":""org.batfish.datamodel.routing_policy.statement.If"",""falseStatements"":[{""class"":""org.batfish.datamodel.routing_policy.statement.Statements$StaticStatement"",""type"":""Return""}],""guard"":{""class"":""org.batfish.datamodel.routing_policy.expr.BooleanExprs$StaticBooleanExpr"",""type"":""CallExprContext""}}]}"

## SubnetworkPolicyMetrics
Counts BGP properties in routing policies between routers within a subnetwork.

In [15]:
result = bf.q.subnetworkPolicyMetrics().answer().frame()
result

,Node_Policy,Community_Set_Vals,Set_Metric,Match_Community_Vals,Local_Preference
0,atla-re0 NEXT-HOP-SELF,0,0,0,0
1,chic-re0 NEXT-HOP-SELF,0,0,0,0
2,clev-re0 NEXT-HOP-SELF,0,0,0,0
3,hous-re0 NEXT-HOP-SELF,0,0,0,0
4,kans-re0 NEXT-HOP-SELF,0,0,0,0
5,losa-re0 NEXT-HOP-SELF,0,0,0,0
6,newy-re0 NEXT-HOP-SELF,0,0,0,0
7,salt-re0 NEXT-HOP-SELF,0,0,0,0
8,seat-re0 NEXT-HOP-SELF,0,0,0,0
9,wash-re0 NEXT-HOP-SELF,0,0,0,0
10,TOTAL,0,0,0,0